FROM mcr.microsoft.com/devcontainers/python:3.11

# Caso precise instalar alguma dependência a nível de sistema operacional no futuro, 
# basta descomentar as linhas abaixo:
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <pacotes>
